# Generated by Django 3.2.12 on 2023-08-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='destination',
            name='Country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
