# Generated by Django 3.2.12 on 2023-08-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20230811_2006'),
        ('main_app', '0002_auto_20230811_2033'),
    ]

    operations = [
    ]
