# Generated by Django 4.2.4 on 2023-08-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_comment_rating_alter_train_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='train',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.train'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=250),
        ),
    ]
