# Generated by Django 4.2.4 on 2023-08-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20230811_2033'),
        ('main_app', '0003_alter_booking_schedule_alter_booking_user_and_more'),
    ]

    operations = [
    ]
