# Generated by Django 4.2.4 on 2023-08-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDestinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_arrival', models.DateTimeField()),
                ('date_time_departure', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.destination')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='schedule',
        ),
        migrations.AddField(
            model_name='booking',
            name='train',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.train'),
        ),
        migrations.AddField(
            model_name='route',
            name='train',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.train'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AddField(
            model_name='routedestinationschedule',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.route'),
        ),
        migrations.AddField(
            model_name='destination',
            name='routes',
            field=models.ManyToManyField(through='main_app.RouteDestinationSchedule', to='main_app.route'),
        ),
    ]
