# Generated by Django 4.2.4 on 2023-08-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_routedestinationschedule_remove_booking_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='routedestinationschedule',
            name='date_time_arrival',
        ),
        migrations.RemoveField(
            model_name='routedestinationschedule',
            name='date_time_departure',
        ),
        migrations.AddField(
            model_name='routedestinationschedule',
            name='scheduling_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.schedulinginfo'),
        ),
    ]
