# Generated by Django 4.2.4 on 2023-08-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_schedulinginfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulinginfo',
            name='arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulinginfo',
            name='departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
