# Generated by Django 4.2.4 on 2023-08-16 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_schedulinginfo_arrival_schedulinginfo_departure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='routedestinationschedule',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='routedestinationschedule',
            name='route',
        ),
        migrations.RemoveField(
            model_name='routedestinationschedule',
            name='scheduling_info',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='luggage_weight',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='num_passengers',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='train',
        ),
        migrations.RemoveField(
            model_name='route',
            name='name',
        ),
        migrations.RemoveField(
            model_name='route',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(default='A1', max_length=10),
        ),
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='route',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.train'),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='RouteDestinationSchedule',
        ),
        migrations.DeleteModel(
            name='SchedulingInfo',
        ),
        migrations.AddField(
            model_name='stationorder',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.route'),
        ),
        migrations.AddField(
            model_name='stationorder',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.station'),
        ),
        migrations.AddField(
            model_name='journey',
            name='route',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.route'),
        ),
        migrations.AddField(
            model_name='journey',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.train'),
        ),
        migrations.AddField(
            model_name='booking',
            name='journey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.journey'),
        ),
    ]
